# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=123, upload_to='media/'),
            preserve_default=False,
        ),
    ]
