# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 16, 1, 51, 799617)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 16, 1, 51, 799617)),
        ),
    ]
