# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200627_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
