# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200627_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 16, 3, 3, 973221)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 16, 3, 3, 973221)),
        ),
    ]
