# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activationKey',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
